# Generated by Django 6.1 on 2026-08-22 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название привычки",
                        max_length=100,
                        verbose_name="Habit name",
                    ),
                ),
                (
                    "habit_location",
                    models.CharField(
                        help_text="место, в котором необходимо выполнять привычку",
                        max_length=100,
                        verbose_name="Habit Place",
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(
                        help_text="Время, когда неоюходимо выполнить привычку",
                        verbose_name="Habit Action Time",
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        help_text=" действие, которое представляет собой привычка",
                        verbose_name="Habit Action",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Признак приятной привычки",
                        verbose_name="Is Habit Pleasant",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневная"),
                            ("Weekly", "Еженедельная"),
                            ("Monthly", "Ежемесячная"),
                        ],
                        default="daily",
                        verbose_name="Habit Period",
                    ),
                ),
                (
                    "bonus",
                    models.CharField(
                        default="Печенька",
                        help_text="Вознаграждение за выполнение привычки",
                        max_length=200,
                        verbose_name="Habit Bonus",
                    ),
                ),
                (
                    "time_for_action",
                    models.TextField(
                        help_text="Время на выполнение привычки",
                        verbose_name="Habit Time For Action",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Признак публичности привычки",
                        verbose_name="Habit Public Habit",
                    ),
                ),
                (
                    "connected_habit",
                    models.ForeignKey(
                        help_text="привычка, которую можно привязать к выполнению полезной привычки",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="habits.habit",
                        verbose_name="Habit Connected",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Создатель привычки",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Habit Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
