# Generated by Django 6.1 on 2026-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action_time',
            field=models.CharField(help_text='Время, когда необходимо выполнить привычку', verbose_name='Habit Action Time'),
        ),
    ]
