# Generated by Django 6.0.8 on 2026-08-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0008_habit_last_reminder_date_alter_habit_bonus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="bonus",
            field=models.CharField(
                blank=True,
                help_text="Вознаграждение за выполнение привычки",
                max_length=200,
                null=True,
                verbose_name="Habit Bonus",
            ),
        ),
    ]
