# Generated by Django 6.0.8 on 2026-09-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0009_alter_habit_bonus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["id"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
